[frame.app]
    name = "example"

[frame.http]
    port = 8080
    host = "localhost"
    debug = true
    pprof = true

[frame.metrics]
    namespace = "frame"
    name = "example"
    port = 10106

[frame.log]
    file_name = "example"
    path = "/data/log"
    max_size = 500
    max_backups = 10
    max_age = 7
    compress = false
    encoding = "json"